apiVersion: v1
data:
  config.yaml: |-
    enableNodeSelector: false
    mountPodPatch:
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: dingofs-csi-driver
    app.kubernetes.io/name: dingofs-csi-driver
    app.kubernetes.io/version: master
  name: dingofs-csi-driver-config
  namespace: dingofs